### ISSUE TITLE
Dereferencing of the null pointer might take place in peconv::is_valid_sectons_alignment

### ISSUE THREAD

**Issue by xtahi0nix** [hasherezade/libpeconv#14]
It's me again:)

In pe_hdrs_helper.cpp:

        PIMAGE_SECTION_HEADER next_sec = peconv::get_section_hdr(payload, payload_size, i);
        const DWORD next_sec_addr = is_raw ? (next_sec->PointerToRawData) : (next_sec->VirtualAddress);

There might be dereferencing of a potential null pointer "next_sec"

**Comment by hasherezade** [comment]
Thanks for the patient audit :)
Indeed this condition could possibly occur if the sections count in the File Header is set into some big, invalid number (going beyond the PE size).

**Comment by xtahi0nix** [comment]
You're welcome:)))
