### ISSUE TITLE
issue with load_pe_module

### ISSUE THREAD

**Issue by 11philip22** [hasherezade/libpeconv#23]
Hi there,
I am trying to load a DLL from a byte array with the  load_pe_module function. I tried replicating the methods in https://github.com/hasherezade/libpeconv/blob/master/tests/test_load_ntdll.cpp. But when i call a function from the loaded DLL i am getting an access violation exception :(
````cpp
#include <Windows.h>

#include <peconv.h>
#include "Payload.h"

//typedef int (*moduleMainProc)();
int(_cdecl* moduleMain) () = NULL;

int main()
{
	size_t v_size = 0;
	BYTE* payloadModule = peconv::load_pe_module(
		payload, 
		sizeof(payload), 
		v_size, 
		true, 
		true
	);
	if (!payloadModule) {
		return -1;
	}

	bool is64 = peconv::is64bit(payloadModule);
	FARPROC nOffset = peconv::get_exported_func(payloadModule, (LPSTR)"main");
	if (nOffset == nullptr) {
		return -1;
	}

	int (*loaded_pe_entry)(void) = (int (*)(void)) nOffset;
	return loaded_pe_entry();
	
	//moduleMain = (int(_cdecl*) ()) nOffset;
	//return moduleMain();
}
````
![exception](https://user-images.githubusercontent.com/26529935/106775281-41efab00-6643-11eb-9363-7efae0f8d5ce.png)
Am i doing something wrong or is there an issue with the lib or my dll?
This is the dll that im using: https://github.com/11philip22/DllShellSimple

**Comment by hasherezade** [comment]
hi!
can you share the exact builds of the library that you are using? I will check.
you can drop them here as an attachment.

**Comment by hasherezade** [comment]
Check if those builds work for you:
[DllShellSample_builds.zip](https://github.com/hasherezade/libpeconv/files/5920752/DllShellSample_builds.zip)

**Comment by 11philip22** [comment]
> hi!
> can you share the exact builds of the library that you are using? I will check.
> you can drop them here as an attachment.

These are the files that i'm trying to load.
[dll.zip](https://github.com/hasherezade/libpeconv/files/5924598/dll.zip)



> Check if those builds work for you:
> [DllShellSample_builds.zip](https://github.com/hasherezade/libpeconv/files/5920752/DllShellSample_builds.zip)

Sadly i'm getting the same results
![exception2](https://user-images.githubusercontent.com/26529935/106874088-13b6ad80-66cd-11eb-9f32-5de60a7ca52a.png)

I also forgot to mention that i had to put some casts at line 11, 22 and 23 in hooks.cpp to make it compile in visual studio.
![cast](https://user-images.githubusercontent.com/26529935/106875281-6775c680-66ce-11eb-9ba1-d77d7b2adcfe.png)
I ran this snippet from your ntdll test to make sure libpeconv still works after applying those casts.
````cpp
#include <Windows.h>

#include <peconv.h>

int(_cdecl* ntdll_tolower) (int) = NULL;

int main()
{
    size_t v_size = 0;
    BYTE* ntdll_module = peconv::load_pe_module("C:\\Windows\\system32\\ntdll.dll", v_size, true, true);
    if (!ntdll_module) {
        return -1;
    }

    bool is64 = peconv::is64bit(ntdll_module);
    std::cout << "NTDLL loaded" << is64 << std::endl;
    FARPROC n_offset = peconv::get_exported_func(ntdll_module, (LPSTR)"tolower");
    if (n_offset == NULL) {
        return -1;
    }

    std::cout << "Got tolower: " << n_offset << std::endl;
    ntdll_tolower = (int(_cdecl*) (int)) n_offset;
    int out = ntdll_tolower('C');
    std::cout << "To lower char: " << (char)out << std::endl;
}
````
![result](https://user-images.githubusercontent.com/26529935/106876136-51b4d100-66cf-11eb-9305-26e89396757d.png)
And it apears to work correctly

**Comment by hasherezade** [comment]
Something is odd. I tested the builds that I shared with you ( [dll.zip](https://github.com/hasherezade/libpeconv/files/5924598/dll.zip) ) and they both loaded fine with libpeconv.
Maybe something is wrong with your loader? Try to use this ready made template: https://github.com/hasherezade/libpeconv_tpl and just change the loaded function prototype...
I will check your builds in the meanwhile.

**Comment by hasherezade** [comment]
ah, I just noticed right now: you used `load_pe_module` - this function doesn't load imports:

```cpp
    /**
    Reads PE from the given file into memory and maps it into vitual format.
    (Automatic raw to virtual conversion).
    If the executable flag is true, the PE file is loaded into executable memory.
    If the relocate flag is true, applies relocations. Does not load imports.
    Automatically allocates buffer of the needed size (the size is returned in outputSize). The buffer can be freed by the function free_pe_buffer.
    */
    BYTE* load_pe_module(const char *filename, OUT size_t &v_size, bool executable, bool relocate);
```
you should use another variant from the API: `load_pe_executable`:

```cpp
    /**
    Loads full PE from file in a way in which it can be directly executed: remaps to virual format, applies relocations, loads imports.
    Allows for supplying custom function resolver.
    */
    BYTE* load_pe_executable(const char *filename, OUT size_t &v_size, t_function_resolver* import_resolver=NULL);
```
...and then everything should be fine.
NTDLL is a special case that doesn't have any imports, that's why both ways it will work.
Either way, I strongly recommend you using [the template](https://github.com/hasherezade/libpeconv_tpl), rather than modifying test cases.

**Comment by 11philip22** [comment]
Yay! I got it to work! Thanks for your help. Everything works as expected with ``load_pe_executable``. Here is the src if you are interested:
````cpp
#include <Windows.h>

#include <peconv.h>
#include "Payload.h"

//typedef int (*moduleMainProc)();
int(_cdecl* moduleMain) () = NULL;

int main()
{
	size_t v_size = 0;
	BYTE* payloadModule = peconv::load_pe_executable(
		payload,
		sizeof(payload),
		v_size
	);
	if (!payloadModule) {
		return -1;
	}

	bool is64 = peconv::is64bit(payloadModule);
	FARPROC nOffset = peconv::get_exported_func(payloadModule, (LPSTR)"main");
	if (nOffset == nullptr) {
		return -1;
	}

	//int (*loaded_pe_entry)(void) = (int (*)(void)) nOffset;
	//int ret = loaded_pe_entry();
	//return ret;
	
	moduleMain = (int(_cdecl*) ()) nOffset;
	return moduleMain();
}
````
Too bad bad windows defender flags it as wacatac but i think that's the case with everything that loads a PE. i think turning it into another DLL will fix that haha.
Anyways thanks a lot for the help :)
