### ISSUE TITLE
Can't use library

### ISSUE THREAD

**Issue by gamethrower** [hasherezade/libpeconv#27]
I tried including both `peconv.h` and compiled `libpeconv.lib` but I keep getting linker errors. Did I miss something?

**Comment by hasherezade** [comment]
Hi! You need a full directory [`includes`](https://github.com/hasherezade/libpeconv/tree/master/libpeconv/include) - not only `peconv.h`. It will go similar to [this example](https://github.com/hasherezade/pe-sieve/wiki/2.1.-How-to-add-PE-sieve-to-your-Visual-Studio-project).

I will make a Wiki page especially for LibPeConv, and explain this.

**Comment by hasherezade** [comment]
Try following [this guide](https://github.com/hasherezade/libpeconv/wiki/How-to-add-LibPEConv-to-your-Visual-Studio-project)
