### ISSUE TITLE
Tls Callbacks

### ISSUE THREAD

**Issue by Tzaxast** [hasherezade/libpeconv#29]
Some pe files have tls callbacks that need to be executed for the pe file to run properly.
Does the library support executing the tls callbacks when mapping and running a pe file from memory?

**Comment by hasherezade** [comment]
hi @Tzaxast ! Sorry for the late response. I added support for TLS Callbacks (for now it is in a separate branch, [tls_support](https://github.com/hasherezade/libpeconv/tree/tls_support) ). Please let me know if everything is fine!

**Comment by hasherezade** [comment]
The TLS Callbacks are not run automatically, but you can run them as presented in the demo case:
https://github.com/hasherezade/libpeconv/blob/tls_support/tests/test_tls_callbacks.cpp
