### ISSUE TITLE
Start windows 7 notepad.exe fail

### ISSUE THREAD

**Issue by wch1618** [hasherezade/libpeconv#44]
Here is code,
```cpp
    size_t v_size = 0;
    LPCTSTR pe_path = "C:\\windows\\notepad.exe";
    BYTE* my_pe = peconv::load_pe_executable(pe_path, v_size);

    if (!my_pe) {
        return -1;
    }

    peconv::set_main_module_in_peb((HMODULE)my_pe);
    
    peconv::run_tls_callbacks(my_pe, v_size);
    
    DWORD ep_rva = peconv::get_entry_point_rva(my_pe);
    if (!ep_rva) {
        return -2;
    }
    ULONG_PTR ep_va = ep_rva + (ULONG_PTR) my_pe;

    int (*new_main)() = (int(*)())ep_va;

    return new_main();
```
Thanks

**Comment by hasherezade** [comment]
Hi @wch1618 ! sorry for the late response, I am nowadays very busy.

So, there are two main problems with notepad.exe:
First of  all, it uses Delayload Imports in additional to the casual imports, but this can be resolved easily with `libPeConv`, just add this fragment after the PE loading:

```cpp
// load delayed imports (if present):
const ULONGLONG loadBase = (ULONGLONG)g_Payload;
peconv::load_delayed_imports(g_Payload, loadBase);
```
But there is a second thing, a bit more problematic - notepad it  sensitive to the path it is loaded from. Even if you copy the original notepad.exe on the Desktop, it won't run.
You may ask, where does it come from?
There is a function [`LoadAcceleratorsW`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadacceleratorsw) called at RVA `0x13807` and `0x13824` in the Notepad, which basically loads some GUI properties (including the menu), but if the application name is different than expected, the proper accelerator table cannot be found, so the Notepad exits.

![load_acc](https://user-images.githubusercontent.com/3115348/184386160-727623dd-4f05-401a-ba25-737eead4c5c8.png)

What are the workarounds for this? You can either hook those functions / patch the checks, and make the notepad load even without the menu. Or another option is to spoof the main path.

I managed to run notepad with the help of this loader: https://gist.github.com/hasherezade/0de5a78264c323172f3a2ad5b89a3b0a

**Comment by wch1618** [comment]
Thank you very much.
