### ISSUE TITLE
Greek_To_me.bin?

### ISSUE THREAD

**Issue by harryeetsource** [hasherezade/libpeconv#48]
Hello I was wondering if this file is currently in use for compiling the code and what its functionality is. Thank you for the fast response to my earlier issue,

**Comment by hasherezade** [comment]
hi! it is just used as a testcase for automated tests of libPeConv. This binary is one of the old FlareOn Challenges (it is mentioned in the relevant test code).
More about it here:
https://hshrzd.wordpress.com/2017/11/24/import-all-the-things-solving-flareon-challenge-3-with-libpeconv/

**Comment by harryeetsource** [comment]
Thank you for clarification!
