### ISSUE TITLE
Provide builds of pe_unmapper via GitHub releases

### ISSUE THREAD

**Issue by seanthegeek** [hasherezade/libpeconv#50]
Please provide builds of `pe_unmapper` via GitHub releases instead of Google Drive. This would allow it to be included as a [package](https://github.com/mandiant/VM-Packages/) in [FLARE VM](https://github.com/mandiant/flare-vm).

**Comment by hasherezade** [comment]
ok, I will l do it soon

**Comment by seanthegeek** [comment]
Thanks! I proposed the FLARE-VM package here https://github.com/mandiant/VM-Packages/issues/184
