### ISSUE TITLE
 libpeconv to run netsh.exe failed

### ISSUE THREAD

**Issue by zmkeh** [hasherezade/libpeconv#60]
I tried to use libpeconv to run netsh.exe in memory.but the process crashed, I also tried to find out why, but failed again. do you know why?

**Comment by hasherezade** [comment]
Hi @zmkeh! This is because this netsh.exe uses MUI. Applications with MUI are not supported. Check out the detailed explanation here: https://github.com/hasherezade/libpeconv/issues/44
